### ISSUE TITLE
.

### ISSUE THREAD

**Issue by krircc** [tokio-cn/tokio-cn.github.io#1]
目前[tokio-zh](https://tokio-zh.github.io)已经有了一个初步完整的翻译，细节需要完善。官方的意思是tokio.rs将使用原生的hugo国际化功能，一旦就绪官方希望中文内容转移到官网去.

**Comment by krircc** [comment]
目前新官网的中文站点已经指向[tokio-zh](https://tokio-zh.github.io/)，这里有一个官方国际化计划的[issues](https://github.com/tokio-rs/website/issues/206)

**Comment by hltj** [comment]
好啊，正有此意。
我刚看到官方添加中文链接了，也看到你差不多都已经翻译完了，很赞。正打算联系你呢。
我也看下官方国际化计划。
